spring:
  application:
    name: ecommerce-app
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:ecommerce;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092

jwt:
  issuer: sky-ecommerce
  secret: ${JWT_SECRET}
  access-token:
    ttl: 15m
  refresh-token:
    ttl: 7d

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

topics:
  order-events: order.events
  payment-events: payment.events
  inventory-events: inventory.events
  notification-events: notification.events

outbox:
  relay:
    interval-ms: 1000

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    com.sky_ecommerce: DEBUG
